#!/usr/bin/env bash
# mkrootfs.sh — Convert rootfs/ directory into an embedded C source file.
#
# Output: $(BUILD_DIR)/rootfs_data.c  (compiled & linked into the kernel)
#
# The generated file defines:
#   - rootfs_file_t  rootfs_files[]
#   - int            rootfs_file_count
#   - const char    *rootfs_get_file(const char *path, unsigned long *size_out)

set -e

ROOTFS_DIR="$1"
OUTPUT_FILE="$2"

if [ -z "$ROOTFS_DIR" ] || [ -z "$OUTPUT_FILE" ]; then
    echo "Usage: $0 <rootfs-dir> <output-c-file>"
    exit 1
fi

if [ ! -d "$ROOTFS_DIR" ]; then
    echo "Error: rootfs directory '$ROOTFS_DIR' not found"
    exit 1
fi

mkdir -p "$(dirname "$OUTPUT_FILE")"

# Header
cat > "$OUTPUT_FILE" << 'CHEADER'
/*
 * rootfs_data.c — Embedded root filesystem (auto-generated by mkrootfs.sh)
 *
 * DO NOT EDIT — regenerate with: make rootfs
 */
#include <shlte/types.h>
#include <string.h>

typedef struct {
    const char *path;      /* e.g. "etc/init.sh" (no leading /) */
    const unsigned char *data;
    unsigned long size;
    int          mode;     /* Unix permission bits */
} rootfs_file_t;

CHEADER

# Build the file table array — collect printable ASCII as C strings,
# binary content as hex byte arrays.
echo "/* --- file entries --- */" >> "$OUTPUT_FILE"

file_index=0
declare -a FILE_PATHS

# Collect files into a temp list to avoid process-substitution issues
FILES_LIST=$(mktemp)
find "$ROOTFS_DIR" -type f -print0 > "$FILES_LIST"

while IFS= read -r -d '' f; do
    fname="${f##*/}"  # basename
    # Store path relative to ROOTFS_DIR
    rel="${f#$ROOTFS_DIR}"
    # Strip leading / if present
    rel="${rel#/}"
    FILE_PATHS+=("$rel")

    # Sanitize the C variable name
    var_name="rootfs_data_${file_index}"

    filesize=$(stat -c%s "$f")

    # Check if the file is "text-like" (printable ASCII with no null bytes)
    if grep -qvP '[^\x20-\x7e\n\r\t]' "$f" 2>/dev/null && [ "$filesize" -lt 4096 ]; then
        # Text content: emit as C string literal
        echo "/* ${rel} (${filesize} bytes, text) */" >> "$OUTPUT_FILE"
        echo "static const unsigned char ${var_name}[] =" >> "$OUTPUT_FILE"
        # Use od to produce safe C string
        od -An -v -tx1 "$f" | tr -d '\n' | sed 's/  */ /g' | \
            awk '{
                printf "    \""
                for (i = 1; i <= NF; i++) {
                    printf "\\x%s", $i
                }
                printf "\"\n"
            }' >> "$OUTPUT_FILE"
        echo ";" >> "$OUTPUT_FILE"
    else
        # Binary content: emit as hex byte array
        if [ "$filesize" -gt 2097152 ]; then
            echo "Warning: $rel is $filesize bytes (large binary, may increase kernel size)" >&2
        fi
        echo "/* ${rel} (${filesize} bytes, binary) */" >> "$OUTPUT_FILE"
        echo "static const unsigned char ${var_name}[] = {" >> "$OUTPUT_FILE"
        # Use Python for reliable hex encoding (avoids xxd/fold splitting issues)
        python3 -c "
import sys
with open('$f', 'rb') as fh:
    data = fh.read()
    parts = []
    for b in data:
        parts.append(f'0x{b:02x}')
    # Wrap at 12 bytes per line (each byte = '0xNN, ' = 6 chars including space)
    # 12 bytes = 72 chars per line max
    for i in range(0, len(parts), 12):
        chunk = parts[i:i+12]
        print('    ' + ', '.join(chunk) + ',')
" >> "$OUTPUT_FILE"
        echo "};" >> "$OUTPUT_FILE"
    fi

    # Determine file mode
    if [ -x "$f" ]; then
        mode="0755"
    else
        mode="0644"
    fi

    echo "/* ${rel} / ${mode} */" >> "$OUTPUT_FILE"

    file_index=$((file_index + 1))
done < "$FILES_LIST"
rm -f "$FILES_LIST"

# Write the file table
echo "" >> "$OUTPUT_FILE"
echo "/* --- file table --- */" >> "$OUTPUT_FILE"
echo "static rootfs_file_t rootfs_files[] = {" >> "$OUTPUT_FILE"

for i in "${!FILE_PATHS[@]}"; do
    rel="${FILE_PATHS[$i]}"
    # Determine file mode
    f="$ROOTFS_DIR/$rel"
    if [ -x "$f" ]; then
        mode="0755"
    else
        mode="0644"
    fi
    echo "    {\"${rel}\", rootfs_data_${i}, sizeof(rootfs_data_${i}), 0${mode}}," >> "$OUTPUT_FILE"
done

echo "};" >> "$OUTPUT_FILE"
echo "static const int rootfs_file_count = ${#FILE_PATHS[@]};" >> "$OUTPUT_FILE"

# Lookup function
cat >> "$OUTPUT_FILE" << 'CFOOTER'

const unsigned char *rootfs_get_file(const char *path, unsigned long *size_out, int *mode_out)
{
    if (!path || !size_out) return NULL;

    /* Strip leading '/' */
    if (path[0] == '/') path++;

    /* Strip leading "./" */
    if (path[0] == '.' && path[1] == '/') path += 2;

    for (int i = 0; i < rootfs_file_count; i++) {
        if (strcmp(rootfs_files[i].path, path) == 0) {
            *size_out = rootfs_files[i].size;
            if (mode_out) *mode_out = rootfs_files[i].mode;
            return rootfs_files[i].data;
        }
    }
    return NULL;
}

int rootfs_get_count(void)
{
    return rootfs_file_count;
}

const char *rootfs_get_name(int index)
{
    if (index < 0 || index >= rootfs_file_count) return NULL;
    return rootfs_files[index].path;
}
CFOOTER

echo "[OK] RootFS data generated: $OUTPUT_FILE (${#FILE_PATHS[@]} files)"
